export default {
    SET_MEDIAS: "SET_MEDIAS",
    ADD_MEDIA: "ADD_MEDIA",
    EDIT_MEDIA: "EDIT_MEDIA",
    DELETE_MEDIA: "DELETE_MEDIA",
    SET_MEDIA: "SET_MEDIA",
    SET_EDIT_INDEX: "SET_EDIT_INDEX",
    SET_FORMULAS: "SET_FORMULAS",
    SET_OBJETIVO: "SET_OBJETIVO",
    SAVE: "SAVE",
    READ: "READ"

}